<?php
echo "<!DOCTYPE html>\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "    <meta charset=\"utf-8\">\n"; 
echo "    <title>Form Collection.php</title>\n"; 
echo "</head>\n"; 
echo "<body>\n"; 
echo "    <form action=\"/echo.php\" id=\"myForm\">\n"; 
echo "        First Name:<br><input type=\"text\" name=\"firstName\" id=\"firstName\"><br><br>\n"; 
echo "        Last Name:<br><input type=\"text\" name=\"lastName\" id=\"lastName\"><br><br>\n"; 
echo "        Favorite Color: \n"; 
echo "        <select name=\"color\">\n"; 
echo "            <option value=\"red\">Red</option>\n"; 
echo "            <option value=\"white\">White</option>\n"; 
echo "            <option value=\"blue\">Blue</option>\n"; 
echo "        </select><br><br>\n"; 
echo "        Method: <select id=\"mySelect\" onchange=\"selectMethod()\">\n"; 
echo "            <option value=\"GET\">GET\n"; 
echo "            <option value=\"POST\">POST\n"; 
echo "        </select><br><br>\n"; 
echo "        <input type=\"submit\" value=\"Submit\" style=\"float: left\">\n"; 
echo "    </form>\n"; 
echo "\n"; 
echo "    <script>\n"; 
echo "        function selectMethod(){\n"; 
echo "            var selAct = document.getElementById(\"mySelect\").value;\n"; 
echo "            document.getElementById(\"myForm\").setAttribute(\"method\", selAct.toLowerCase());\n"; 
echo "        }\n"; 
echo "    </script>\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>
